<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>XiaoEr</AssemblyName>
    <RootNamespace>Workbench</RootNamespace>
    <Product>小二</Product>
    <Company>小二</Company>
    <ApplicationIcon>Assets\XiaoEr.ico</ApplicationIcon>
    <Version>1.3.8</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishReadyToRun>false</PublishReadyToRun>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Installer\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\XiaoEr.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>
</Project>
